src/components/shared/Navbar.tsx, src/pages/Administrations/AllStaffs.tsx, src/pages/Administrations/AllStaffs/OfficeStaffs.tsx, src/pages/Administrations/AllStaffs/SupportingStaffs.tsx, src/pages/Administrations/AllStaffs/Teachers.tsx, src/routes/Routes.tsx
=> updating administrations

src/components/layout/Dashboard/DashboardLayout.tsx, src/components/layout/Dashboard/Sidebar.tsx, src/components/shared/Navbar.tsx, src/pages/Student/StudentProfile.tsx, src/routes/Routes.tsx
=> Dashboard layout added

src/pages/Home/AuthoritySection/AuthorityCard.tsx, src/pages/Home/GreetingsSection/GreetingCard.tsx
=> updating greetingsCard

src/components/shared/Navbar.tsx, src/index.css, src/pages/Authentication/Login.tsx, src/pages/Authentication/SignUp.tsx, src/pages/Dashboard/Student/StudentProfile.tsx, src/pages/Home/Home/Home.tsx, tailwind.config.js
update navbar, login, signup page
=> update navbar, login, signup page

package.json, src/components/shared/Navbar.tsx, src/pages/Administrations/Messages/HeadMastersMessages.tsx, src/pages/Authentication/Login.tsx, src/pages/Home/AlumniMarquee/AlumniMarquee.tsx, src/pages/Home/AlumniMarquee/Marquee.tsx, src/pages/Home/GreetingsSection/GreetingCard.tsx, src/pages/Home/GreetingsSection/GreetingsSection.tsx, src/pages/Home/Home/Home.tsx, src/pages/Home/SubscriptionBox/SubscriptionBox.tsx, src/pages/Resources&Events/Events/EventsPage.tsx, src/pages/Resources&Events/Results/ResultsPage.tsx, src/routes/Routes.tsx, src/utils/cn.tsx, tailwind.config.js
alumni marquee, navbar & dropdown menu updated, subscription form design updated, result page created
=> alumni marquee, navbar & dropdown menu updated, subscription form design updated, result page created

src/pages/Authentication/SignUp.tsx
password validation for registration page
=> password validation

package.json, src/main.tsx, src/pages/Authentication/SignUp.tsx, src/types/UserTypes.ts
creating student with tanstack query
=> creating student with tanstack query

src/pages/Authentication/SignUp.tsx, src/types/UserTypes.ts
Changed nothing, worked for the backend
=> Changed nothing, worked for the backend

src/pages/Authentication/SignUp.tsx, vite.config.ts
vite configuration and signUp page with axios changed
=> vite configuration and signUp page with axios changed

src/pages/Authentication/Login.tsx, src/pages/Authentication/SignUp.tsx
=> Succesfull login

package.json, src/Context/UserContext.tsx, src/components/shared/HotlineNavbar.tsx, src/main.tsx, src/pages/Authentication/Login.tsx, src/types/UserTypes.ts
creating userContext for user authentication
=> creating userContext for user authentication

src/Context/UserContext.tsx, src/Context/useUser.ts, src/components/shared/HotlineNavbar.tsx, src/pages/Authentication/Login.tsx, src/pages/Authentication/Logout.tsx, src/pages/Authentication/SignUp.tsx, src/routes/PrivateRoute.tsx, src/routes/Routes.tsx, src/types/UserTypes.ts
user authentication & private route
=> user authentication & private route

src/Context/useUser.ts, src/pages/Dashboard/Student/StudentProfile.tsx, src/pages/Home/AlumniMarquee/AlumniMarquee.tsx, src/types/UserTypes.ts
update useUser hook and create student profile
=> update useUser hook and create student profile

src/pages/Dashboard/Student/StudentProfile.tsx
=> updating student profile page

src/components/layout/Dashboard/DashboardLayout.tsx, src/components/layout/Dashboard/Sidebar.tsx, src/components/shared/Navbar.tsx, src/hooks/useDashboardUrl.ts, src/pages/Dashboard/Student/MyResults.tsx, src/routes/Routes.tsx, src/types/UserTypes.ts
=> dashboard based on user role

src/components/shared/Navbar.tsx, src/hooks/useDashboardUrl.ts, src/pages/Authentication/Login.tsx, src/pages/Authentication/SignUp.tsx, src/pages/Dashboard/Student/StudentProfile.tsx
=> Login and signUp issue

package.json, src/components/shared/HotlineNavbar.tsx, src/components/shared/Navbar.tsx
=> Hotline Navbar and navbar

src/components/shared/Navbar.tsx, src/components/ui/PageWrapper.tsx, src/pages/Administrations/Messages/HeadMastersMessages.tsx, src/pages/Administrations/Messages/PrincipalsMessage.tsx, src/pages/Authentication/Login.tsx, src/pages/Authentication/SignUp.tsx, src/pages/Blog/Blog.tsx, src/pages/Home/Slider/Slider.tsx
PageWrapper component for animation, Login , signup, Messages from authority, and the login and singup fixed for small screen size
=> PageWrapper component for animation, Login , signup, Messages from authority, and the login and singup fixed for small screen size

src/hooks/ScrollGrowHook.tsx, src/pages/Authentication/SignUp.tsx, src/pages/Home/AuthoritySection/AuthorityCard.tsx, src/pages/Home/GreetingsSection/GreetingCard.tsx, src/pages/Home/SubscriptionBox/SubscriptionBox.tsx, src/types/UserTypes.ts
useScroll hook with framer-motion
=> useScroll hook with framer-motion

src/pages/Dashboard/Student/StudentProfile/EditProfileModal.tsx, src/pages/Dashboard/Student/StudentProfile/StudentProfile.tsx, src/types/UserTypes.ts
=> Student Profile edit

src/pages/Dashboard/Student/StudentProfile/EditProfileModal.tsx, src/pages/Dashboard/Student/StudentProfile/StudentProfile.tsx
implement imgbb api for image upload
=> implement imgbb api for image upload

src/pages/Home/AlumniMarquee/AlumniMarquee.tsx
=> updated alumniMarque

src/pages/Resources&Events/Results/ResultsPage.tsx, src/utils/accordion.tsx
result page created and shown public results
=> result page created and shown public results

src/components/ui/Button.tsx, src/pages/Home/AlumniMarquee/AlumniMarquee.tsx, src/pages/Home/GallerySection/GallerySection.tsx, src/pages/Home/Home/Home.tsx, src/pages/Home/HomeScreenNavigation/ButtonGroups.tsx, src/pages/Home/Slider/Slider.tsx, src/utils/Button.tsx
=> ButtonGroups

src/components/api/Result.api.ts, src/pages/Resources&Events/Results/ResultsPage.tsx
=> result page modified

src/Context/useUser.ts, src/pages/Authentication/Login.tsx, src/pages/Authentication/SignUp.tsx, src/pages/Dashboard/Student/StudentProfile/EditProfileModal.tsx
fixed the student routes in frontend
=> fixed the student routes in frontend

src/pages/Authentication/SignUp.tsx, src/pages/Dashboard/Student/StudentProfile/StudentProfile.tsx
updated signup page notification
=> updated signup page notification

src/components/layout/Dashboard/DashboardLayout.tsx, src/pages/Administrations/Messages/HeadMastersMessages.tsx, src/pages/Administrations/Messages/PrincipalsMessage.tsx, src/pages/Authentication/SignUp.tsx, src/pages/Dashboard/Student/StudentProfile/StudentProfile.tsx, src/pages/Home/Home/Home.tsx, src/pages/Resources&Events/Results/ResultsPage.tsx
=> updated dashboard
